#!/usr/bin/env bash

## #lodev-generated
## Description: Open PHPStorm with the current project
## Usage: phpstorm
## Example: "lodev phpstorm"

# Example is macOS-specific, but easy to adapt to any OS
open -a PHPStorm.app ${LODEV_APPROOT}
