#!/usr/bin/env bash

## #lodev-generated
## Description: Run magento CLI inside the web container
## Usage: magento [flags] [args]
## Example: "lodev magento list" or "lodev magento maintenance:enable" or "lodev magento sampledata:reset"
## ProjectTypes: magento
## ExecRaw: true

cd "${LODEV_COMPOSER_ROOT:-/var/www/html}" || exit 1

if [ ! -f bin/magento ]; then
  echo 'bin/magento does not exist in your project composer_root directory.'
  echo 'Please verify that you installed the shop in your project directory.'
  exit 1
fi

php bin/magento "$@"
