#!/usr/bin/env bash

## #lodev-generated
## Description: Run n98-magerun2 CLI inside the web container
## Usage: magerun2 [flags] [args]
## Example: "lodev magerun2 sys:cron:list"
## ProjectTypes: magento
## ExecRaw: true

cd "${LODEV_COMPOSER_ROOT:-/var/www/html}" || exit 1

if [ ! -f bin/magento ]; then
  echo 'Magento can not installed in this directory.'
  echo 'Please verify that you installed the shop in your project directory.'
  exit 1
fi

magerun2 "$@"
