#!/usr/bin/env bash
#lodev-generated
## Description: Run WordPress CLI inside the web container
## Usage: wp [flags] [args]
## Example: "lodev wp core version" or "lodev wp plugin install user-switching --activate"
## ProjectTypes: wordpress,wp-bedrock
## ExecRaw: true

# Ignore anything we find in the mounted global commands
PATH=${PATH//\/mnt\/lodev_default\/commands\/web/}

# Add --path if not already set and $LODEV_DOCROOT is defined
if [[ ! " $* " =~ (--path(=|\s)) ]] && [[ -n "$LODEV_DOCROOT" ]]; then
  # Get the configured path from wp-cli.yml or other config file
  existing_wp_path="$(yq -r '.path // ""' "$(wp cli info --format=json 2>/dev/null | jq -r '.project_config_path // empty' 2>/dev/null)" 2>/dev/null)"
  # If there is no path, set it to $LODEV_DOCROOT
  [[ -z "$existing_wp_path" ]] && set -- "$@" --path="$LODEV_DOCROOT"
fi

wp "$@"
