package nodeps

import (
	"runtime/debug"
)

// VersionConstraint is the version constraint for services in the registry, used to ensure compatibility between LODEV and services
const VersionConstraint = ">= 0.1.0"

// LodevVersion is the current version of LODEVs
var LodevVersion = ""

// LodevFileSignature is the signature that is added to the top of all files generated by LODEV, used to identify and manage those files
const LodevFileSignature = "#lodev-generated"

func init() {
	if LodevVersion != "" {
		return
	}
	// Get version from build
	if v := deriveVersionFromBuildInfo(); v != "" {
		LodevVersion = v
		return
	}
	// Fallback to "dev" if we can't determine a version from build info
	LodevVersion = "v0.0.0-dev"
}

// deriveVersionFromBuildInfo uses Go's embedded VCS info (enabled by default since Go 1.18+)
// to produce a short commit-based version like "gabcd123[-dirty]".
func deriveVersionFromBuildInfo() string {
	bi, ok := debug.ReadBuildInfo()
	if !ok {
		return ""
	}

	return bi.Main.Version
}
